site:
  title: Antora Docs
  start_page: rp-antora:en:rancher-manager.adoc
content:
  sources:
  - url: ./
ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files
asciidoc:
  attributes:
    page-pagination: ''
  extensions:
  - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
